name: 'Conda Package Publish Action'
description: 'Build and Publish conda package'
author: 'Angus Gibson'
branding:
  icon: 'package'
  color: 'purple'
inputs:
  subDir:
    description: 'Sub-directory with project'
    default: '.'
  AnacondaUsername:
    description: 'Anaconda Username'
  AnacondaPassword:
    description: 'Anaconda Password'
  label:
    description: 'Label to pass to Anaconda upload'
    default: 'main'
  channels:
    description: 'Space-delimited list of Anaconda channels to use'
runs:
  using: 'docker'
  image: 'Dockerfile'
